# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_razorpay_dev
  username: dell
  password: 123456

production:
  <<: *default
  database: rails_razorpay_pro
  username: dell
  password: 123456

